### PR TITLE
WIP: I will implement exercise isogram

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
All done :)

**Comment by sdavids13** [comment]
Thanks! Can you quick fix the build? It failed with:

> Running configlet...
Evaluating .
-> config.json does not include [isogram].

All we need to do is add the module name to the config.json file (found in the project's root directory). The ordering is based on complexity relative to the other projects.

**Comment by geoand** [comment]
Sorry about the break! 
It troubled me but I spot the error :(

I'll fix it as soon as have access to a computer.
Thanks!

**Comment by geoand** [comment]
All good to go :)

**Comment by sdavids13** [comment]
Awesome, thanks!

**Comment by geoand** [comment]
You're welcome!
I will try to do some more problems at the first opportunity

**Comment by kotp** [comment]
Is this still WIP as titled? Or should the title be changed?

**Comment by geoand** [comment]
It has been merged, so the work completed

**Comment by kotp** [comment]
Yes, I figured that, so the title of WIP title is not valid any longer, so should it be changed?

**Comment by geoand** [comment]
I don't know what the policy is on that. Perhaps @sdavids13 has more insight

**Comment by sdavids13** [comment]
Makes sense to drop the WIP, I went ahead and did so.

**Comment by kytrinyx** [comment]
When I do WIP commits, the WIP is to make sure people don't merge it before I'm ready. When I'm ready for it to be merged, I rebase my PR, squash whichever commits it makes sense to squash, make sure my commit messages are solid, and then edit the title of the PR to remove the WIP. Then I add a comment on the PR to also say that I'm ready for another review.

**Pull request merged**
