### PR TITLE
Create hello-world exercise

### PR DESCRIPTION
**Pull request by cswagner**
Adds the hello-world exercise to the Kotlin track.

### CODE REVIEW

**Comment by kytrinyx** [comment]
I'm not sure it makes sense to stick the gradlew / gradlew.bat files in the exercise itself. I seem to recall going through some iterations of figuring this out in the Java track.  Since the CLI currently gets the exercise data in JSON format (each file is an entry in the JSON) I think it might have blown up with the scripts. Or not. I don't recall.

@exercism/java do any of you recall what happened with this?

**Comment by jtigger** [comment]
Before I arrived on the scene, the decision had been made not to use the wrapper, but to walk folks through the Gradle install (or have them use IntelliJ's built-in support).  Very likely for the reason you state: we don't deliver JARs through the CLI.

In fact, what's good for the goose...  might want to take a look at the xjava build structure.

**Comment by cswagner** [comment]
Thanks for the feedback. I've updated to not use the Gradle wrapper.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by ErikSchierboom** [comment]
Great news! Looking forward to this track

**Pull request merged**
