### PR TITLE
Normalize format of config file

### PR DESCRIPTION
**Pull request by kytrinyx**
This will let us script changes to it with less noise in the diffs.

### CODE REVIEW

**Comment by stkent** [comment]
This broke in some interesting way. I'm guessing some `configlet` change, maybe, since when I run the unit tests script locally I also see failures with no changes in master. Whatever the issue is, it's the same in `xkotlin`, so I assigned myself to all the related issues while I investigate.

See https://github.com/exercism/configlet/compare/v1.1.0...v2.0.0 for the relevant configlet changes.

**Comment by stkent** [comment]
Confirmed, if I update the `unit-tests` script to explicitly use configlet v1.1.0 (the prior release to today's v2.0.0) then unit tests run fine. Reading that diff more closely...

**Comment by kytrinyx** [comment]
@stkent I made those changes in Configlet—how can I help?

**Comment by kytrinyx** [comment]
> config.json does not include [_template].

Where is `_template`?

**Comment by stkent** [comment]
@kytrinyx the output I'm seeing is this warning:

```
config.json does not include [_template].
```

However, I see it in the current config file:

```
"ignored": [
  "_template",
  ".gradle",
  "build",
  "docs",
  "gradle",
  "scripts"
],
```

I have just started to look at the configlet diff posted above; perhaps your more experienced eyes can spot any regression there faster than I will be able to? ❤️ 🤞

**Comment by kytrinyx** [comment]
This is the problem: https://github.com/exercism/xkotlin/tree/master/exercises/_template

@stkent The assumption we make is that every directory within `exercises` is an exercise. If you place the `_template` in the root, that would fix this.

**Comment by stkent** [comment]
There's a `_template` dir nested in `exercises` that is meant to be the seed for new exercises.

**Comment by stkent** [comment]
Ahh, gotcha, thanks!. Which line of configlet is hiccuping there (for my own edification)?

**Comment by kytrinyx** [comment]
It's not a configlet problem, it's a conceptual problem. We used to tell Configlet to ignore directories named certain things (per the config.json). When we removed that, configlet assumes that every single directory it finds within the exercises directory is an exercise. The code is here: https://github.com/exercism/configlet/blob/master/configlet/track.go#L100-L123

**Comment by kytrinyx** [comment]
The change that caused this to fail is removing the IgnoredDirs() here: https://github.com/exercism/configlet/pull/17/files#diff-40e62472ea4139af33eebcc8f65668ebL94

**Comment by stkent** [comment]
Ah ha! In that case I would humbly suggest that for clarity we might want to update the error message:

```
config.json does not include [_template].
```

to something more explicit like:

```
Exercise named _template found in exercises directory but not declared in the exercises block in config.json.
```

(This assumes I caught your drift properly (finally).)

**Comment by kytrinyx** [comment]
> (This assumes I caught your drift properly (finally).)

Haha yes. You did.

So... you could also stick it in "deprecated" in config.json, which would mean that configlet would stop complaining about it.

I will update the error message, though. That's a good call.

**Comment by stkent** [comment]
I've relocated the template to the root dir in both xkotlin and xjava; that seems cleaner than deprecating a fake exercise. Thanks for taking on the error message update!

**Comment by stkent** [comment]
@kytrinyx if you could please rebase this against master, the CI build should now pass!

**Comment by kytrinyx** [comment]
w00t! Thank you!

**Comment by stkent** [comment]
Build is timing out; Travis seems 🐌 tonight. Trying again tomorrow.

**Comment by stkent** [comment]
Build still timing out today 🤔. Gonna play with some speedups here. @sdavids13 can you see anything in the [recent commit history](https://github.com/exercism/xkotlin/commits/master) that might be slowing down recent builds?

**Comment by stkent** [comment]
I'm going to rebase so it builds within the 50 minute limit!

**Comment by kytrinyx** [comment]
> I'm going to rebase so it builds within the 50 minute limit!

A most excellent measure!

**Comment by sdavids13** [comment]
Are there going to be merge conflict headaches with https://github.com/exercism/xkotlin/pull/51?

**Comment by stkent** [comment]
Yes, but I'm happy to take care of fixing up #51.

**Pull request merged**
