### PR TITLE
Skip all but the first test in each exercise.

### PR DESCRIPTION
**Pull request by jtigger**
- adjust in-repo builds to remove ignores.
- for each test, output tests skipped, passed, and failed.

### CODE REVIEW

**Comment by jtigger** [comment]
Implements #25.

**Comment by sdavids13** [comment]
This looks good to me, should we wait to merge this in until some help documentation is available to let them know to remove the `@Ignore` annotations?

**Comment by jtigger** [comment]
I don't think so.  I'll be submitting a PR tomorrow morning that includes those instructions complete with a step-by-step tutorial for `hello-world`.

Since the other PR is waiting on this one, I'd recommend merging this in.

**Comment by sdavids13** [comment]
👍  Awesome, thanks.

**Pull request merged**
