### PR TITLE
triangle: add to track

### PR DESCRIPTION
**Pull request by nithia**

### CODE REVIEW

**Comment by sdavids13** [comment]
Sweet, thanks for the pull request. I checked out some other language tracks and most of them seem to return a TriangleKind/TriangeType enum ([java](https://github.com/exercism/xjava/blob/master/exercises/triangle/src/example/java/Triangle.java#L20), [csharp](https://github.com/exercism/xcsharp/blob/master/exercises/triangle/Example.cs#L13), [scala](https://github.com/exercism/xscala/blob/master/exercises/triangle/example.scala#L4)). I think we should go with that pattern for conformity sake, here is a sample implementation:

```
diff --git a/exercises/triangle/src/example/kotlin/Triangle.kt b/exercises/triangle/src/example/kotlin/Triangle.kt
index af394b0..e69889e 100644
--- a/exercises/triangle/src/example/kotlin/Triangle.kt
+++ b/exercises/triangle/src/example/kotlin/Triangle.kt
@@ -5,9 +5,16 @@ class Triangle<out T: Number>(val a: T, val b: T, val c: T) {
         require(a + b >= c && b + c >= a && c + a >= b, { "Sides must satisfy triangle inequality"})
     }
 
-    val isEquilateral = a == b && b == c
-    val isIsosceles = a == b || b == c || c == a
-    val isScalene = !isIsosceles
+    private fun isEquilateral() = a == b && b == c
+    private fun isIsosceles() = a == b || b == c || c == a
+
+    fun getType(): TriangleType {
+        return when {
+            isEquilateral() -> TriangleType.EQUILATERAL
+            isIsosceles() -> TriangleType.ISOSCELES
+            else -> TriangleType.SCALENE
+        }
+    }
 
     private infix operator fun <T: Number> T.compareTo(other: T): Int = this.toDouble().compareTo(other.toDouble())
     private infix operator fun <T: Number> T.plus(b: T): Double = this.toDouble().plus(b.toDouble())
diff --git a/exercises/triangle/src/example/kotlin/TriangleType.kt b/exercises/triangle/src/example/kotlin/TriangleType.kt
new file mode 120000
index 0000000..581da9e
--- /dev/null
+++ b/exercises/triangle/src/example/kotlin/TriangleType.kt
@@ -0,0 +1 @@
+../../main/kotlin/TriangleType.kt
\ No newline at end of file
diff --git a/exercises/triangle/src/main/kotlin/TriangleType.kt b/exercises/triangle/src/main/kotlin/TriangleType.kt
new file mode 100644
index 0000000..e2b5987
--- /dev/null
+++ b/exercises/triangle/src/main/kotlin/TriangleType.kt
@@ -0,0 +1,4 @@
+
+enum class TriangleType {
+    EQUILATERAL, ISOSCELES, SCALENE
+}
```

The tests would have to obviously change.

**Comment by nithia** [comment]
Thanks for the review. I went with that sort of implementation originally - it's very natural for an old Java-head like me. But then I saw this issue being pointed at in the test data: https://github.com/exercism/x-common/issues/379 and realised it really did make sense to go with the property-based approach. Please have a look at let me know.

**Comment by jtigger** [comment]
Hey @nithia, sorry for the delay!  This track was a little understaffed for a while.

In light of that discussion, I wholeheartedly agree!  I'll give this PR a formal review...

**Comment by nithia** [comment]
Hey @jtigger, I've made the changes as requested and also upgraded to kotlin 1.0.6 in line with the rest of the exercises. Agree this track could use a few more people on it. I'm completely happy to contribute as time and $dayjob permit :) Kotlin is a lot of fun & I'm looking forward to the 1.1 release.

**Comment by jtigger** [comment]
Yikes @nithia!  Sorry for the super long delay!

Thanks for making those edits.  This looks really good.  Appreciate your help!

**Pull request merged**
